name: CI/CD with Carbon Awareness

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  carbon-aware-ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js (or any environment you are using)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Carbon Aware Action
        uses: carbon-aware-action@v1
        with:
          # You can specify the environment or other settings if needed
          environment: production  # Optional: set your environment, e.g., staging or production

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy (or other steps)
        run: |
          # Your deploy step here, e.g., deploying to AWS, DigitalOcean, etc.
          echo "Deploying to production..."
